server:
  port: 5555

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - "routes"

zuul:
  sensitive-headers:
    - Cookie, Authorization