version: '3.1'

services:
  provider-db:
    image: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: provider

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 9090:8080