version: '3.1'

services:
  store-db:
    image: postgres
    ports:
      - "5433:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: store

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 9090:8080