version: '3.1'

services:
  transporter-db:
    image: postgres
    ports:
      - "5434:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: transporter

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 9090:8080